#!/usr/bin/env php
<?php
require 'vendor/autoload.php';

use Rewake\AliasBuilder\BuildAliasesCommand;
use Symfony\Component\Console\Application;

// Create application
$app = new Application('BABS Alias Builder Script', '1.0.0');

// Instantiate build command
$command = new BuildAliasesCommand();

// Add command to app and set as default
$app->add($command);
$app->setDefaultCommand($command->getName(), true);

// Run the app
$app->run();
