#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Dotenv\Dotenv;
use Rewake\BuildAliasesCommand;
use Symfony\Component\Console\Application;

// Load .env
(Dotenv::createImmutable(__DIR__))->safeLoad();

$app = new Application('BABS Alias Builder Script', '1.0.0');

$command = new BuildAliasesCommand();

$app->add($command);
$app->setDefaultCommand($command->getName(), true);
$app->run();